### ISSUE TITLE
Results Not Matching with Table 2

### ISSUE THREAD

**Issue by kaliaanup** [nbalepur/DynaMiTE#3] opened 2024-04-16 18:25 UTC
Hi Thanks for organizing the datasets. 

For each dataset given the seed words in the paper, I obtained the test.txt files with evolving topics. After running the eval I am getting the following. I was trying to match the results with Table 2 but I guess it does not really match.

|data   |           pmi        |     npmi       |       lcp        |      diversity|
|---- |            ----         | ----             |            ---- | ----             |
|arxiv      |       0.702312  |  0.077952 |   -0.283055 |  1.0 |
|un-debates |  0.244851 |  0.023682 |    -0.322926 |   1.0 |
|newspop. |      0.71346   |   0.089052 |    -0.488389 |   1.0 |

I wonder how to interpret this result with Table 2 in the paper.

For your convenience I have attached the results folder.
[results.zip](https://github.com/nbalepur/DynaMiTE/files/15001177/results.zip)

This folder contains only test.txt for each.

**Comment by nbalepur** [comment] 2024-04-16 19:02
Thanks for checking this out! 

So the NMPI results in our table are just multiplied by 100. There was another paper we saw that did this, and I think we discuss this somewhere in the paper? If that's not the case I will update this repo accordingly.

So it looks like your Arxiv results matches ours (0.077952 * 100 = 7.80). The newspop result is actually higher than what we reported, but I think the reason is because it looks like you just used "technology" and "politics" as the seeds, but we actually used "technology, microsoft" for the first topic evolution and "politics, president_barack_obama" for the second (see last line of section 5.1). 

I have no idea what's up with UN. My best guess is that there's some difference in how we are parsing the data (or maybe I shared an incorrect dataset with you). Let me take a look this week! Glad you were able to reproduce our Arxiv results

**Comment by kaliaanup** [comment] 2024-04-16 19:11
This is a great feedback. I will work on newspop based on your suggestion. Kindly check for UN.

**Comment by nbalepur** [comment] 2024-05-25 19:49
Sorry this took me so long to get back to you. I was able to reproduce our results and get an NPMI value of 8.3149 on UN using the seeds "disaster" and "leader" (slightly higher than the value of 8.28 reported in the paper, but likely just due to noise in the topic mining algorithm)

I'll close this issue for now, but feel free to re-open if you're still having issues. I can also send you the preprocessed data or hop on a call if you would like to discuss things further!

**Closed as completed by nbalepur** 2024-05-25 19:49 UTC
